platform :ios,'9.0'
target 'APP' do

pod 'AFNetworking', '~> 3.2.1'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.6'
pod 'MJExtension', '~> 3.0.15.1'
pod 'SDWebImage', '~> 4.4.2'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'Bugly', '~> 2.5.0'
pod 'FMDB', '~> 2.7.2'
#pod 'JKCategories', '~> 1.7'
pod 'Colours', '~> 5.13.0'
pod 'YYText', '~> 1.0.7'
pod 'Popover.OC', '~> 2.2'
pod 'SDCycleScrollView', '~> 1.75'
pod 'QBPopupMenu', '~> 2.0'
pod 'WMPageController', '~> 2.5.2'
pod 'IQKeyboardManager', '~> 6.1.1'
pod 'SDAutoLayout', '~> 2.2.1'
pod 'HJTabViewController', '~> 1.0.6'
pod 'JPush', '~> 3.1.0'
pod 'HXWeiboPhotoPicker', '~> 2.1.5'
pod 'KSPhotoBrowser', '~> 0.2.3'
pod 'JYHHHorizontalPagingView', '~> 1.2.1'
pod 'ZFPlayer', '~> 3.1.6'
pod 'lottie-ios', '~> 2.5.0'
pod 'Charts', '~> 3.1.1'

end

